#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: 'Colette & Mark • 10/29/2016'
baseurl: 'http://therewillbepie2016.com'
description: 'Tying the knot on a love grown from Pi Day.'
timezone: America/Los_Angeles
googleanalytics: UA-26097728-8

share:
  image: /img/share.jpg
  width: 1200
  height: 630
  title: Colette & Mark are tying the knot!
  description: Take a second to say congratulations.

#############
# Authoring #
#############

future: true
show_drafts: true
permalink: /:categories/:month/:day/:title/

collections:
  root:
    permalink: /:title
    output: true
  static_pages:
    permalink: /:path/
    output: true

defaults:
  - scope:
      path: ''
      type: root
    values:
      layout: none
  - scope:
      path: ''
      type: static_pages
    values:
      layout: default
  - scope:
      path: ''
    values:
      layout: 'default'

prose:
  rooturl: 'app'
  ignore:
    - '_data'
    - '_includes'
    - '_js'
    - '_layouts'
    - '_less'
    - '_root'
    - 'favicon.ico'
  siteurl: 'http://therewillbepie2016.com/'
  media: 'app/img'
  metadata:
    app/updates:
      - name: title
        field:
          element: text
          label: Title
          placeholder: 'My Blog Post Title'
          help: 'This is the title that appears at the top of the page.'
      - name: description
        field:
          element: textbox
          label: 'Description (optional)'
          help: 'The description text that appears on Google. (sometimes just the first paragraph of your post).'
          type: 'text'
      - name: share_title
        field:
          element: text
          label: 'Share Title (optional)'
          placeholder: 'You won’t believe what happens next'
          help: 'If you want a different title to appear on facebook or twitter.'
      - name: share_description
        field:
          element: textbox
          label: 'Share Description (optional)'
          placeholder: 'You won’t believe what happens next'
          help: 'If you want a different description to appear on facebook or twitter.'
      - name: 'share_image'
        field:
          element: 'text'
          label: 'Share image (optional)'
          help: 'Use the image insert functionality to upload a picture, then paste the file name here. (make sure you delete it from your post, too, if you don’t want it there!)'
          placeholder: 'your-filename.jpg'
          type: 'text'
      - name: 'share_width'
        field:
          element: 'text'
          label: 'Share image width (optional)'
          help: 'Whole number, no units.'
          placeholder: '1200'
          type: 'text'
      - name: 'share_height'
        field:
          element: 'text'
          label: 'Share image height (optional)'
          help: 'Whole number, no units.'
          placeholder: '630'
          type: 'text'

#############
# Compiling #
#############

exclude: ['img']
keep_files: ['img', 'js', 'css']

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ['apos', 'apos', 'quot', 'quot']
