#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: 'Colette & Mark • 10/29/2016'
url: 'http://therewillbepie2016.com'
description: 'Tying the knot on a love grown from Pi Day.'
timezone: America/Los_Angeles
googleanalytics: UA-26097728-8

share:
  image: /img/share.jpg
  width: 1200
  height: 630
  title: Colette & Mark are tying the knot!
  description: Take a second to say congratulations.

#############
# Authoring #
#############

future: true
show_drafts: true
permalink: /:categories/:month/:day/:title/

collections:
  root:
    permalink: /:title
    output: true
  static_pages:
    permalink: /:path/
    output: true

defaults:
  - scope:
      path: ''
      type: root
    values:
      layout: none
  - scope:
      path: ''
      type: static_pages
    values:
      layout: default
  - scope:
      path: ''
    values:
      layout: 'default'

#############
# Compiling #
#############

exclude: ['img']
keep_files: ['img', 'js', 'css']

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ['apos', 'apos', 'quot', 'quot']
